class Time:
    def __init__(self, nome, pais, chave, escudo):
        self.nome = nome
        self.pais = pais
        self.chave = int(chave)
        self.escudo = escudo

TeamsDic = {}
TeamsList = []


TeamsDic['Bayern'] = Time('Bayern', 'Alemanha', '1', 'Times/Bayern.png')
TeamsList.append('Bayern')
TeamsDic['Sevilla'] = Time('Sevilla', 'Espanha', '1', 'Times/Sevilla.png')
TeamsList.append('Sevilla')
TeamsDic['Real Madrid'] = Time('Real Madrid', 'Espanha', '1', 'Times/Real_Madrid.png')
TeamsList.append('Real Madrid')
TeamsDic['Liverpool'] = Time('Liverpool', 'Inglaterra', '1', 'Times/Liverpool.png')
TeamsList.append('Liverpool')
TeamsDic['Juventus'] = Time('Juventus', 'Italia', '1', 'Times/Juventus.png')
TeamsList.append('Juventus')
TeamsDic['PSG'] = Time('PSG', 'Franca', '1', 'Times/PSG.png')
TeamsList.append('PSG')
TeamsDic['Zenit'] = Time('Zenit', 'Russia', '1', 'Times/Zenit.png')
TeamsList.append('Zenit')
TeamsDic['Porto'] = Time('Porto', 'Portugal', '1', 'Times/Porto.png')
TeamsList.append('Porto')
TeamsDic['Barcelona'] = Time('Barcelona', 'Espanha', '2', 'Times/Barcelona.png')
TeamsList.append('Barcelona')
TeamsDic['Atletico Madrid'] = Time('Atletico Madrid', 'Espanha', '2', 'Times/Atletico_Madrid.png')
TeamsList.append('Atletico Madrid')
TeamsDic['Man United'] = Time('Manchester United', 'Inglaterra', '2', 'Times/Manchester_United.png')
TeamsList.append('Man United')
TeamsDic['Manchester City'] = Time('Manchester City', 'Inglaterra', '2', 'Times/Manchester_City.png')
TeamsList.append('Manchester City')
TeamsDic['Shaktar Donetsk'] = Time('Shaktar Donetsk', 'Ucrania', '2', 'Times/Shakhtar_Donetsk.png')
TeamsList.append('Shaktar Donetsk')
TeamsDic['Borussia Dortmund'] = Time('Borussia Dortmund', 'Alemanha', '2', 'Times/Borussia_Dortmund.png')
TeamsList.append('Borussia Dortmund')
TeamsDic['Chelsea'] = Time('Chelsea', 'Inglaterra', '2', 'Times/Chelsea.png')
TeamsList.append('Chelsea')
TeamsDic['Ajax'] = Time('Ajax', 'Holanda', '2', 'Times/Ajax.png')
TeamsList.append('Ajax')
TeamsDic['Dynamo Kiev'] = Time('Dynamo Kiev', 'Ucrania', '3', 'Times/Dynamo_Kiev.png')
TeamsList.append('Dynamo Kiev')
TeamsDic['RB Salzburg'] = Time('RB Salzburg', 'Alemanha', '3', 'Times/RB_Salzburg.png')
TeamsList.append('RB Salzburg')
TeamsDic['RB Leipzig'] = Time('RB Leipzig', 'Alemanha', '3', 'Times/RB_Leipzig.png')
TeamsList.append('RB Leipzig')
TeamsDic['Internazionale'] = Time('Internazionale', 'Italia', '3', 'Times/Internazionale.png')
TeamsList.append('Internazionale')
TeamsDic['Olympiacos'] = Time('Olympiacos', 'Grecia', '3', 'Times/Olympiakos.png')
TeamsList.append('Olympiacos')
TeamsDic['Lazio'] = Time('Lazio', 'Italia', '3', 'Times/Lazio.png')
TeamsList.append('Lazio')
TeamsDic['Krasnodar'] = Time('Krasnodar', 'Russia', '3', 'Times/Krasnodar.png')
TeamsList.append('Krasnodar')
TeamsDic['Atalanta'] = Time('Atalanta', 'Italia', '3', 'Times/Atalanta.png')
TeamsList.append('Atalanta')
TeamsDic['Lokomotiv Moscou'] = Time('Lokomotiv Moscou', 'Russia', '4', 'Times/Lokomotiv_Moscou.png')
TeamsList.append('Lokomotiv Moscou')
TeamsDic['OL Marseille'] = Time('Olympique Marselhe', 'Franca', '4', 'Times/Olympique_Marselha.png')
TeamsList.append('OL Marseille')
TeamsDic['Club Brugge'] = Time('Club Brugge', 'Belgica', '4', 'Times/Club_Brugge.png')
TeamsList.append('Club Brugge')
TeamsDic['B. Monchengladbach'] = Time('Borussia Monchengladbach', 'Alemanha', '4', 'Times/Borussia_Monchengladbach.png')
TeamsList.append('B. Monchengladbach')
TeamsDic['I. Basakehir'] = Time('Istanbul Basakehir', 'Turquia', '4', 'Times/Istanbul Basaksehir.png')
TeamsList.append('I. Basakehir')
TeamsDic['Midtjylland'] = Time('Midtjylland', 'Dinamarca', '4', 'Times/Midtjylland.png')
TeamsList.append('Midtjylland')
TeamsDic['Rennes'] = Time('Rennes', 'Franca', '4', 'Times/Rennes.png')
TeamsList.append('Rennes')
TeamsDic['Ferencvaros'] = Time('Ferencvaros', 'Hungria', '4', 'Times/Ferencvaros.png')
TeamsList.append('Ferencvaros')
